### ISSUE TITLE
Hard coded parameters

### ISSUE THREAD

**Issue by aprest10** [ExpenseTracking/expenseTrackerUI#20]
Hey @MarkCodez, please check this code when you can, looks like you still have the hard coded value in the parameter and its been copied into your other methods in this file.

https://github.com/ExpenseTracking/expenseTrackerUI/blob/70a554e1d8956b8d85ff48f570bbc9292fd428f7/src/app/Home/service-revenue/service-revenue.component.ts#L48

**Comment by MarkCodez** [comment]
thanks for catching that @aprest10! I modified the components that use the 'userId' field to be the user's id that is authenticated. no more hard code.
